### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by pinkman2010** [gentiansl/python-coding-challenge#1]
Hi thanks for this python code challenge,

I want to ask you about filter and sort.

How do you want to filter or sort data, i mean from database or direct from csv file ?
If from database should i create an extra endpoint to store data from csv to database ?

Thanks in advance.

**Comment by gentiansl** [comment]
Hello,

Thanks for the interest, and your question.

We want you to see how would you manage working with a database.
So, in this instance you can save the data from the csv file in a database.

Filtering and sorting the data is when we want to expose the data (from db) through endpoints.
Meaning, it's not relevant how the data is stored in database. But how they're exposed through the API.
As per storing the data in the DB, whichever method is more convenient for you.

I hope that answers your question, if you need more information please let me know.

Thank you.

**Comment by pinkman2010** [comment]
Thanks.
